import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}//${geistSans.variable} ${geistMono.variable}
    >
      <body className="min-h-screen flex flex-col">
        <div className="box-border flex-1 w-full max-w-xl mx-auto border-2 border-gray-100 rounded-xl overflow-hidden bg-gray-500">



          {children}
        </div>
      </body>
    </html>
  );
}
